export const posts = [
  {
    _id: "1",
    title: "Fashion",
    slug: "fashion",
    img: "/blog/fashion.png",
    createdAt: "2023-10-01",
    catSlug: "fashion",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    _id: "2",
    title: "Lifestyle",
    slug: "lifestyle",
    img: "/blog/style.png",
    createdAt: "2023-10-01",
    catSlug: "lifestyle",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    _id: "3",
    title: "Travel",
    slug: "travel",
    img: "/blog/travel.png",
    createdAt: "2023-10-01",
    catSlug: "travel",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    _id: "4",
    title: "Food",
    slug: "food",
    img: "/blog/food.png",
    createdAt: "2023-10-01",
    catSlug: "food",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    _id: "5",
    title: "Fitness",
    slug: "fitness",
    img: "/blog/tiktok.png",
    createdAt: "2023-10-01",
    catSlug: "fitness",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
  {
    _id: "6",
    title: "Technology",
    slug: "technology",
    img: "/blog/youtube.png",
    createdAt: "2023-10-01",
    catSlug: "technology",
    desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
  },
];
